### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by littledivy** [DivySrivastava/intellect#3]
`$(".box").fadeOut();` is not working on older android browsers.
I think we should use 
`$(".box")[0].style.display = 'none'` instead.
Need opinion

**Comment by dan-online** [comment]
I would

> `$(".box").fadeOut();
setTimeout(() => {
       if($(".box")[0].style.display != 'none') {
          $(".box")[0].style.display = 'none'
       }
},3000)`

and also add 
> ``.box {
    transition: display 1s;
}``

**Comment by littledivy** [comment]
Cool! I'll close the issue now
