### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by dan-online** [DivySrivastava/intellect#5]
- Needs Margin on question pages 
 - ~Need to decide whether we are using the jokes anymore on the loading page as you can't read them.~ 
 - Choose a new color - Looks too much like spruce
 - Notification tabs - Bottom of the page tabes
 - Icon needs whitespace for app icon, maybe a dif file

**Comment by littledivy** [comment]
I thinks jokes should be removed

**Comment by dan-online** [comment]
I agree and it's done

**Comment by littledivy** [comment]
Cool

**Comment by littledivy** [comment]
Why did I close that! Lol

**Comment by dan-online** [comment]
Hahah loll

**Comment by littledivy** [comment]
Should I create a `bottom navbar` like the one in Spruce?

**Comment by dan-online** [comment]
Ye, also, can we consider a different color scheme, it looks too much like spruce

**Comment by littledivy** [comment]
I agree
