### ISSUE TITLE
/search and /ask are the same thing...

### ISSUE THREAD

**Issue by littledivy** [DivySrivastava/intellect#6]
The '/search?q=My+question' and '/ask?q=My+question' is the same thing..
The only difference is the "Ask New Question" form in '/ask'.
I think we should remove '/search'

**Comment by dan-online** [comment]
/search is a much better fuzzy search

**Comment by littledivy** [comment]
It is basically like StackOverflow
Where you search for similar question and if none exists you ask one

**Comment by dan-online** [comment]
Yea but you can search questions too. Also the /search endpoint is much more advanced in searching

**Comment by littledivy** [comment]
I merged both of them..just check it out

**Comment by littledivy** [comment]
I merged both of them..just check it out
